# Generated by Django 2.1.7 on 2019-04-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'base_organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('phone_number', models.TextField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'contact_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_en', models.TextField()),
                ('name_fr', models.TextField()),
                ('street_address', models.TextField()),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('postal_code', models.TextField()),
                ('country', models.TextField()),
                ('website_url', models.TextField()),
                ('main_telephone', models.TextField()),
                ('logo_path', models.TextField()),
                ('is_research_funder', models.BooleanField(max_length=100)),
                ('is_research_org', models.BooleanField(max_length=100)),
                ('is_business', models.BooleanField(max_length=100)),
                ('is_non_profit', models.BooleanField(max_length=100)),
                ('is_govt', models.BooleanField(max_length=100)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
    ]
