# Generated by Django 2.1.7 on 2019-03-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u15', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_fr', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=100)),
                ('main_telephone', models.CharField(max_length=100)),
                ('logo_path', models.CharField(max_length=100)),
                ('is_research_funder', models.BooleanField(max_length=100)),
                ('is_research_org', models.BooleanField(max_length=100)),
                ('is_business', models.BooleanField(max_length=100)),
                ('is_non_profit', models.BooleanField(max_length=100)),
                ('is_govt', models.BooleanField(max_length=100)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
    ]
