# Generated by Django 2.1.7 on 2019-03-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='institutions',
            new_name='user',
        ),
    ]
