# Generated by Django 2.1.7 on 2019-03-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_baseorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('phone_number', models.TextField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'contact_info',
                'managed': False,
            },
        ),
    ]
